--DROP TABLE IF EXISTS people;
--
--CREATE TABLE people (
--  id INT AUTO_INCREMENT  PRIMARY KEY,
--  husband VARCHAR(250) NOT NULL,
--  wife VARCHAR(250) NOT NULL
--);
--
--INSERT INTO people (husband, wife) VALUES
--  ('Pista', 'Erzsi'),
--  ('Jozsi', 'Kati'),
--  ('Laci', 'Szamanta'),
--  ('Geza', 'Dzsenifer'),
--  ('Feri', 'Erika'),
--  ('Tarzan', 'Klaudia'),
--  ('John', 'Zsanett'),
--  ('Bill', 'Szandra'),
--  ('Vladislav', 'Kriszti'),
--  ('Szergej', 'Anett');